/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const API_VERSION: string
export const API_BASE_URL: string
export class WebSocket { }
export class Client {
  /** Initialize a new Discord client */
  constructor()
}
